// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: train.proto

package trainbookingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrainBookingService_Purchase_FullMethodName = "/train_booking.TrainBookingService/Purchase"
)

// TrainBookingServiceClient is the client API for TrainBookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainBookingServiceClient interface {
	// unary
	Purchase(ctx context.Context, in *TrainBookingRequest, opts ...grpc.CallOption) (*TrainBookingResponse, error)
}

type trainBookingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainBookingServiceClient(cc grpc.ClientConnInterface) TrainBookingServiceClient {
	return &trainBookingServiceClient{cc}
}

func (c *trainBookingServiceClient) Purchase(ctx context.Context, in *TrainBookingRequest, opts ...grpc.CallOption) (*TrainBookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainBookingResponse)
	err := c.cc.Invoke(ctx, TrainBookingService_Purchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainBookingServiceServer is the server API for TrainBookingService service.
// All implementations must embed UnimplementedTrainBookingServiceServer
// for forward compatibility.
type TrainBookingServiceServer interface {
	// unary
	Purchase(context.Context, *TrainBookingRequest) (*TrainBookingResponse, error)
	mustEmbedUnimplementedTrainBookingServiceServer()
}

// UnimplementedTrainBookingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrainBookingServiceServer struct{}

func (UnimplementedTrainBookingServiceServer) Purchase(context.Context, *TrainBookingRequest) (*TrainBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Purchase not implemented")
}
func (UnimplementedTrainBookingServiceServer) mustEmbedUnimplementedTrainBookingServiceServer() {}
func (UnimplementedTrainBookingServiceServer) testEmbeddedByValue()                             {}

// UnsafeTrainBookingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainBookingServiceServer will
// result in compilation errors.
type UnsafeTrainBookingServiceServer interface {
	mustEmbedUnimplementedTrainBookingServiceServer()
}

func RegisterTrainBookingServiceServer(s grpc.ServiceRegistrar, srv TrainBookingServiceServer) {
	// If the following call pancis, it indicates UnimplementedTrainBookingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrainBookingService_ServiceDesc, srv)
}

func _TrainBookingService_Purchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainBookingServiceServer).Purchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainBookingService_Purchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainBookingServiceServer).Purchase(ctx, req.(*TrainBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrainBookingService_ServiceDesc is the grpc.ServiceDesc for TrainBookingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrainBookingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "train_booking.TrainBookingService",
	HandlerType: (*TrainBookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Purchase",
			Handler:    _TrainBookingService_Purchase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "train.proto",
}
